channels:
- conda-forge
- bioconda
dependencies:
- python=3.9
- lammps=2020.10.29=py39_openmpi_2
- pyiron=0.3.18
- jupyter_client=6.1.7
- papermill=2.2.2
- scikit-learn=0.23.2
- nglview=2.7.7
- mscorefonts=0.0.1
- snakemake=5.29.0
